baseURL = 'https://t-c.me'
languageCode = 'en-us'
title = 'Tomáš Chobola'

theme = 'hugo-bearblog'

enableRobotsTXT = true

publishDir = 'docs'

contentDir = 'content'

[params]
  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"
